### ISSUE TITLE
GDWeave has Wacatac trojan - Not a false positive

### ISSUE THREAD

**Issue by RabbitStewGames** [NotNite/GDWeave#27]
Recently Windows Defender has been flagging a potential trojan in winmm.dll, but it's not actually a false positive. A friend of mine had their Steam profile compromised.

The trojan in question is a Wacatac trojan, or a trojan that stealthily performs malicious actions (in this case, sending phishing links to Steam friends) without your knowledge.

Please investigate the latest Thunderstore release, as it may be compromised.

![image](https://github.com/user-attachments/assets/896528b2-4085-445b-8497-3f9743e1df96)
![image](https://github.com/user-attachments/assets/e95dca4e-154e-459f-bde0-170cb4c901cf)
![image](https://github.com/user-attachments/assets/8e287acf-168b-41d4-a279-c4db60d1273f)
![image](https://github.com/user-attachments/assets/28f937a5-2164-42ab-af18-43c04d1180a6)

**Comment by NotNite** [comment]
No, it's not, and I don't appreciate these heavy claims. Your friend must've fallen for something else unrelated, and you incorrectly correlated the two. Closing.

Commit https://github.com/NotNite/GDWeave/commit/32ee3e560743de0346dba1ac906ec9caffa8b5ee changed the hook that initializes GDWeave to happen in the PE entrypoint instead of DllMain. This avoids [loader lock](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices) and allows us to create threads inside of GDWeave mods. This is done by calling `GetModuleInformation` and then using [retour](https://crates.io/crates/retour) to initialize a hook on the EntryPoint pointer.

This sets off false positives in antiviruses - Defender specifies `Trojan:Win32/Wacatac.B!ml`. The `!ml` flag indicates this was through its **m**achine **l**earning model - not a known threat, but an assumed one. This matches with what you reported.

If you don't trust me, you can download the `thunderstore.zip` package from [this GitHub Action run](https://github.com/NotNite/GDWeave/actions/runs/11779302663) built with [this workflow](https://github.com/NotNite/GDWeave/actions/runs/11779302663/workflow) on [this commit](https://github.com/NotNite/GDWeave/commit/30f7a5233b08874f5ea55a9a43486cb8678bc312), along with [the upload to Thunderstore](https://gcdn.thunderstore.io/live/repository/packages/NotNet-GDWeave-2.0.14.zip), and compare the two files:

```pwsh
$ Get-FileHash .\winmm.dll

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          CEB9EDCD52FDCD24ED0BF6C36AF365B9614B7F2BDABCF2916BA01FEF2B9306E8       C:\Users\Julian\Downloads\winmm.dll

$ Get-FileHash .\winmm_thunderstore.dll

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          CEB9EDCD52FDCD24ED0BF6C36AF365B9614B7F2BDABCF2916BA01FEF2B9306E8       C:\Users\Julian\Downloads\winmm_thunderstore.dll
```
